<?php

namespace AppBundle\Repository;

/**
 * ProgressRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProgressRepository extends \Doctrine\ORM\EntityRepository
{
    public function sumForDate($from, $to)
    {
        return $this->createQueryBuilder('progress')
            ->select('SUM(progress.seconds)')
            ->where('progress.createdAt BETWEEN :from AND :to')
            ->setParameter(':from', $from)
            ->setParameter(':to', $to)
            ->getQuery()
            ->getResult();
    }
}
